### ISSUE TITLE
[PE-D][Tester B] No questions and no options displayed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-F15-1/tp#114]
![image.png](https://raw.githubusercontent.com/Zhengwinter/ped/main/files/80fc2b3a-75af-45df-9f37-49a0d8171302.png)

Questions are just displayed as "question 1" and options are displayed as "Option A", "Option B", "Option C" and "Option D", there is no indication as to which options to select.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Zhengwinter/ped#4

**Comment by NGXZS** [comment]
Add mock dataset, so for now considered fix
but you guys feel free to add more questions + topics to make it better :)

**Comment by NGXZS** [comment]
update: 
total 3 topics, each topic got 10 questions
refer to comments in Player2113.java to see how to add more questions
