### ISSUE TITLE
[PE-D][Tester B] No context for explanation, further exposing implementation details

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-F15-1/tp#119]
![image.png](https://raw.githubusercontent.com/Zhengwinter/ped/main/files/2723c0e5-4129-45c5-8c8b-b8b08128f368.png)

Similar to the issue with the solution, the explanation does not offer any clue to the user as to what is going on with the application. 

Piecing together the numbering from explanation and solution further reveals the internal implementation of the application to the user.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Zhengwinter/ped#6

**Comment by NGXZS** [comment]
fix: add mock dataset (questions, explanations, solutions, options etc) : hardcoded tho :(
