### ISSUE TITLE
[PE-D][Tester C] repetition in help command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-F15-1/tp#125]
in the help command, there are repeated examples and details.

![image.png](https://raw.githubusercontent.com/ZhuSijia0711/ped/main/files/f01d708c-6f3c-40a7-ba2d-f636a48df997.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ZhuSijia0711/ped#8

**Comment by NGXZS** [comment]
duplicate #139
