### ISSUE TITLE
[PE-D][Tester D] 'help' command format in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-F15-1/tp#146]
![image.png](https://raw.githubusercontent.com/kyuichyi/ped/main/files/c2d7be43-13c2-4c86-bab6-8261f2cf83db.png)

Format for 'help' command in UG does not follow the rest of the commands.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: kyuichyi/ped#9

**Comment by NGXZS** [comment]
fixed
