### ISSUE TITLE
[Code Review] NGXZS

### ISSUE THREAD

**Issue by nichyjt** [AY2324S2-CS2113-F15-1/tp#64]
### AFI (Code Quality)

`Parser.java`
Refer to the image:
![image](https://github.com/AY2324S2-CS2113-F15-1/tp/assets/69704055/d15c1728-d284-400b-8895-f6db7d306832)
1. Remove unused code. Do not leave them as commented code. Otherwise, a well factored function
2. Magic literals, e.g. `"bye"`

Refer to the image:
![image](https://github.com/AY2324S2-CS2113-F15-1/tp/assets/69704055/975a6bd3-51fa-472f-8354-42ad26faffb4)
1. It is not too nested, which is good. But the method length is quite long. You could consider factoring out some components to make it clearer what each block of code supposed to do.
e.g. The code seems to be checking if the command is of a certain type, then executing its logic then early returning, similar to how a guard clause works. Apart from factoring out logic to make it SLAP, could another design pattern work better in this case?

All the best!

**Comment by NGXZS** [comment]
reviewed, now in Unused folder unfortunately :(
