### ISSUE TITLE
As a new user, I can access the tutorial/guide to the game easily

### ISSUE THREAD

**Issue by cyhjason29** [AY2324S2-CS2113-F15-1/tp#9]
... so that I know how to navigate through the game.

**Comment by songyuew** [comment]
Basic viewing UG function added, specific command guide need to be implemented

**Comment by NGXZS** [comment]
PR fails github 3 checks, rmb to fix them according to tips in the group chat and let us know if you need help!

**Comment by songyuew** [comment]
Sure, now fixing the github checks
